"""add_gmail_oauth_fields

Revision ID: 430b6a47a3a5
Revises: ae4e3c2c5d50
Create Date: 2026-01-26 23:46:33.473403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '430b6a47a3a5'
down_revision: Union[str, None] = 'ae4e3c2c5d50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Use Text for encrypted fields - EncryptedJSON stores encrypted strings, not JSON
    op.add_column('user_settings', sa.Column('gmail_oauth_client', sa.Text(), nullable=True))
    op.add_column('user_settings', sa.Column('gmail_oauth_tokens', sa.Text(), nullable=True))
    op.add_column('user_settings', sa.Column('gmail_connected_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_settings', sa.Column('gmail_email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'gmail_email')
    op.drop_column('user_settings', 'gmail_connected_at')
    op.drop_column('user_settings', 'gmail_oauth_tokens')
    op.drop_column('user_settings', 'gmail_oauth_client')
    # ### end Alembic commands ###
